version: '2'
services:
    cit337project-app:
        image: cit337project
        external_links:
            - cit337project-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cit337project?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cit337project-mysql:
        extends:
            file: mysql.yml
            service: cit337project-mysql
